[theme]
primaryColor="#304666"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
font="sans serif"

[server]
headless = true
maxUploadSize = 20
enableStaticServing = true



[global]
hide_streamlit_branding = false
hide_menu_items = ["Network"]

[client]
showToolbar = false
